apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "cloudflare.cf.sys-int.de/v1alpha1",
          "kind": "ArgoTunnel",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "cf-operator",
              "app.kubernetes.io/instance": "argotunnel-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "argotunnel",
              "app.kubernetes.io/part-of": "cf-operator"
            },
            "name": "argotunnel-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "cloudflare.cf.sys-int.de/v1alpha1",
          "kind": "ArgoTunnelIngressRule",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "cf-operator",
              "app.kubernetes.io/instance": "argotunnelingressrule-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "argotunnelingressrule",
              "app.kubernetes.io/part-of": "cf-operator"
            },
            "name": "argotunnelingressrule-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "cloudflare.cf.sys-int.de/v1alpha1",
          "kind": "DNSRecord",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "cf-operator",
              "app.kubernetes.io/instance": "dnsrecord-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "dnsrecord",
              "app.kubernetes.io/part-of": "cf-operator"
            },
            "name": "dnsrecord-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "cloudflare.cf.sys-int.de/v1alpha1",
          "kind": "Zone",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "cf-operator",
              "app.kubernetes.io/instance": "zone-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "zone",
              "app.kubernetes.io/part-of": "cf-operator"
            },
            "name": "zone-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-08-10T11:27:48Z"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: cf-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ArgoTunnelIngressRule is the Schema for the argotunnelingressrules
        API
      displayName: Argo Tunnel Ingress Rule
      kind: ArgoTunnelIngressRule
      name: argotunnelingressrules.cloudflare.cf.sys-int.de
      version: v1alpha1
    - description: ArgoTunnel is the Schema for the argotunnels API
      displayName: Argo Tunnel
      kind: ArgoTunnel
      name: argotunnels.cloudflare.cf.sys-int.de
      version: v1alpha1
    - description: DNSRecord is the Schema for the dnsrecords API
      displayName: DNSRecord
      kind: DNSRecord
      name: dnsrecords.cloudflare.cf.sys-int.de
      statusDescriptors:
      - description: 'INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
          Important: Run "make" to regenerate code after modifying this file'
        displayName: Conditions
        path: conditions
      version: v1alpha1
    - description: Zone is the Schema for the zones API
      displayName: Zone
      kind: Zone
      name: zones.cloudflare.cf.sys-int.de
      version: v1alpha1
  description: operator to configure cloudflare services
  displayName: cf-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - argotunnelingressrules
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - argotunnelingressrules/finalizers
          verbs:
          - update
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - argotunnelingressrules/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - argotunnels
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - argotunnels/finalizers
          verbs:
          - update
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - argotunnels/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - dnsrecords
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - dnsrecords/finalizers
          verbs:
          - update
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - dnsrecords/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - zones
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - zones/finalizers
          verbs:
          - update
        - apiGroups:
          - cloudflare.cf.sys-int.de
          resources:
          - zones/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: cf-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: cf-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: cf-operator
          control-plane: controller-manager
        name: cf-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: docker.sys-int.de/sys-int/cf-operator:v0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: cf-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: cf-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cloudflare
  - services
  - dns
  - records
  - tunnel
  links:
  - name: Cf Operator
    url: https://cf-operator.domain
  maturity: alpha
  provider:
    name: cf-operator
  version: 0.0.1
